language: objective-c
osx_image: xcode10.1
branches:
  only:
  - master
env:
  - SCHEME="CBL ObjC"
  - SCHEME="CBL Swift"
before_install:
  - brew update
  - brew install doxygen
script: xcodebuild test -project CouchbaseLite.xcodeproj -scheme "$SCHEME" -sdk iphonesimulator -destination "platform=macOS" | xcpretty -c
