language: objective-c
osx_image: xcode10.1
branches:
  only:
  - master
env:
  - SCHEME="CBL ObjC"
  - SCHEME="CBL Swift"
before_install:
  - brew update
  - brew install doxygen
  - gem install slather
script: xcodebuild test -project CouchbaseLite.xcodeproj -scheme "$SCHEME" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS" -enableCodeCoverage YES | xcpretty -c
after_success:
  - test "$SCHEME" = "CBL ObjC" && slather
