#! /bin/bash -e

SCRIPT_DIR=`dirname $0`
pushd "$SCRIPT_DIR/generated" > /dev/null

echo -e "# GENERATED BY generate_exports.sh -- DO NOT EDIT\n"     > CBL.exp
echo -e "# GENERATED BY generate_exports.sh -- DO NOT EDIT\n"     > CBL_EE.exp

cat ../CBL.txt               | sort | awk '/^[._]/ { print $0 }' >> CBL.exp
cat ../CBL.txt ../CBL_EE.txt | sort | awk '/^[._]/ { print $0 }' >> CBL_EE.exp

popd > /dev/null
