Create or open an existing Xcode project and install Couchbase Lite
using one of the following methods.

==== Frameworks

* https://www.couchbase.com/downloads[Download] Couchbase Lite.
* Unzip the file and drag *CouchbaseLiteSwift.framework* from your
Finder to the Xcode navigator.
* Click on *Project > General > Embedded Binary* and add
*CouchbaseLiteSwift.framework* to this section.
* Import the framework and start using it in your project.
+
[source,swift]
----
import CouchbaseLiteSwift
...
----

==== Carthage

1.  https://github.com/Carthage/Carthage#installing-carthage[Install Carthage]
2.  In your *Cartfile*, add the following.
+
*Couchbase Lite Community Edition*
+
[source,ruby]
----
binary "https://raw.githubusercontent.com/couchbase/couchbase-lite-ios/master/Release/Carthage/CouchbaseLite-Community.json" ~> 2.0.0
----
+
*Couchbase Lite Enterprise Edition*
+
[source,ruby]
----
binary "https://raw.githubusercontent.com/couchbase/couchbase-lite-ios/master/Release/Carthage/CouchbaseLite-Enterprise.json" ~> 2.0.0
----
+
3.  Run `carthage update --platform ios`.
4.  Drag *CouchbaseLiteSwift.framework* from *Carthage/Build/* to the Xcode navigator.
5.  Click on Project > General > Embedded Binary and add *CouchbaseLiteSwift.framework* to this section.

==== CocoaPods

1.  https://guides.cocoapods.org/using/getting-started.html[Install
Cocoapods]
2.  In your *Podfile*, add the following.
+
*Couchbase Lite Community Edition*
+
[source,ruby]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite-Swift', '~> 2.0.0'
end
----
+
*Couchbase Lite Enterprise Edition*
+
[source,ruby]
----
target '<your target name>' do
  use_frameworks!
  pod 'CouchbaseLite-Swift-Enterprise', '~> 2.0.0'
end
----
+
3.  Install the pods and open the .xcworkspace file generated by
Cocoapods.
+
[source,bash]
----
pod install
----