#! /bin/bash -e

# Generates the CE and EE private module maps from the header list templates
# (same pattern as Objective-C/Exports/generate_exports.sh):
#   CouchbaseLiteSwift.private.txt       -> Generated/CouchbaseLiteSwift.private.modulemap    (CE)
#   + CouchbaseLiteSwift-EE.private.txt  -> Generated/CouchbaseLiteSwift-EE.private.modulemap (EE)
#
# Template lines starting with '#' are not copied; all other lines are inserted
# verbatim inside the module declaration. The EE module map is the CE header
# list plus the EE-only headers.
#
# Usage:
#   generate_private_modulemap.sh            Regenerate; commit the results.
#   generate_private_modulemap.sh --check    Verify outputs are up to date (CI).

CHECK=""
if [ "$1" == "--check" ]; then
  CHECK=YES
elif [ -n "$1" ]; then
  echo "Usage: $0 [--check]" >&2
  exit 2
fi

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

CE_TEMPLATE="$SCRIPT_DIR/CouchbaseLiteSwift.private.txt"
EE_TEMPLATE="$SCRIPT_DIR/CouchbaseLiteSwift-EE.private.txt"
CE_MODULEMAP="$SCRIPT_DIR/Generated/CouchbaseLiteSwift.private.modulemap"
EE_MODULEMAP="$SCRIPT_DIR/Generated/CouchbaseLiteSwift-EE.private.modulemap"

for t in "$CE_TEMPLATE" "$EE_TEMPLATE"; do
  if [ ! -f "$t" ]; then
    echo "Template not found: $t" >&2
    exit 1
  fi
done

emit_header() {
  echo "//"
  echo "//  $1"
  echo "//  CouchbaseLite"
  echo "//"
  echo "//  Copyright (c) $(date +%Y) Couchbase, Inc All rights reserved."
  echo "//"
  echo "//  Licensed under the Apache License, Version 2.0 (the \"License\");"
  echo "//  you may not use this file except in compliance with the License."
  echo "//  You may obtain a copy of the License at"
  echo "//"
  echo "//  http://www.apache.org/licenses/LICENSE-2.0"
  echo "//"
  echo "//  Unless required by applicable law or agreed to in writing, software"
  echo "//  distributed under the License is distributed on an \"AS IS\" BASIS,"
  echo "//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied."
  echo "//  See the License for the specific language governing permissions and"
  echo "//  limitations under the License."
  echo "//"
  echo "//  GENERATED BY Swift/ModuleMap/generate_private_modulemap.sh -- DO NOT EDIT DIRECTLY."
  echo "//  Edit the header list templates and regenerate."
  echo "//"
  echo ""
}

generate_ce() {
  emit_header "CouchbaseLiteSwift.private.modulemap"
  echo "framework module CouchbaseLiteSwift_Private {"
  grep -v '^#' "$CE_TEMPLATE"
  echo "}"
}

generate_ee() {
  emit_header "CouchbaseLiteSwift-EE.private.modulemap"
  echo "framework module CouchbaseLiteSwift_Private {"
  grep -v '^#' "$CE_TEMPLATE"
  echo ""
  grep -v '^#' "$EE_TEMPLATE"
  echo "}"
}

verify_or_write() {
  local generate_fn="$1" output="$2" name="$3"
  if [ -n "$CHECK" ]; then
    if "$generate_fn" | diff -q "$output" - > /dev/null 2>&1; then
      echo "OK: $name private module map is up to date."
    else
      echo "ERROR: $name private module map is out of date." >&2
      echo "Run '$0' and commit the results." >&2
      exit 1
    fi
  else
    mkdir -p "$(dirname "$output")"
    "$generate_fn" > "$output"
    echo "Generated: $output"
  fi
}

verify_or_write generate_ce "$CE_MODULEMAP" "CE"
verify_or_write generate_ee "$EE_MODULEMAP" "EE"
