name: Swift

on:
  push:
    paths:
      - 'Product.swift'
  pull_request:
    paths:
      - 'Product.swift'

jobs:
  build:
    name: Swift ${{ matrix.swift }}
    strategy:
      matrix:
        swift: ["5.3", "5.3.1", "5.3.2", "5.4", "5.4.2", "5.5"]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
