name: Xcode-Build

on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - '**'

jobs: 
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        scheme: ["CBL_ObjC", "CBL_Swift"]

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive

      - name: "Build-for-testing"
        env:
          SCHEME: ${{ matrix.scheme }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "${SCHEME}" -project CouchbaseLite.xcodeproj  -destination "platform=$platform,name=$device"
      - name: "Test"
        env:
          SCHEME: ${{ matrix.scheme }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | sed 's/Simulator//g' | awk '{$1=$1;print}'`
          xcodebuild test-without-building -scheme "${SCHEME}" -project CouchbaseLite.xcodeproj  -destination "platform=$platform,name=$device"
